# Config.cmake.in


####### Expanded from @PACKAGE_INIT@ by configure_package_config_file() #######
####### Any changes to this file will be overwritten by the next CMake run ####
####### The input file was Config.cmake.in                            ########

get_filename_component(PACKAGE_PREFIX_DIR "${CMAKE_CURRENT_LIST_DIR}/../../../" ABSOLUTE)

####################################################################################

# Value of 'iir_INCLUDE_DIRS' is real: it contains the include directory.
set(iir_INCLUDE_DIRS /home/snehkumar/xTerra/cross-compile/LAIR/custom/install/include)

# CMake extracts a library path from it.
set(iir_LIBRARIES iir)

# Include the export script generated by CMake:
include(${CMAKE_CURRENT_LIST_DIR}/iirTargets.cmake)
